apiVersion: "argoproj.io/v1alpha1"
kind: "Workflow"
metadata:
  generateName: "ogdc-recipe-seal-tags-"
  labels:
    # TODO: What is?
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a spike on our seal tags recipe
spec:
  # The name of the template that will be executed first
  entrypoint: "transform"
  templates:
  - name: "transform"
    inputs:
      artifacts:
        - name: "seal-tags-csv"
          path: "/tmp/foo.csv"
          http:
            url: "https://arcticdata.io/metacat/d1/mn/v2/object/urn%3Auuid%3A31162eb9-7e3b-4b88-948f-f4c99f13a83f"
    container:
      image: "ghcr.io/qgreenland-net/parsl-exploration:v0.2.0"
      command: ["micromamba"]
      args: 
        - "run"
        - "-n"
        - "base"
        - "ogr2ogr"
        - "-lco"
        - "ENCODING=UTF-8"
        - "-t_srs"
        - "EPSG:3413"
        - "-makevalid"
        - "-s_srs"
        - "EPSG:4326"
        - "-oo"
        - "X_POSSIBLE_NAMES=Longitude"
        - "-oo"
        - "Y_POSSIBLE_NAMES=Latitutde"
        - "/tmp/foo.gpkg"
        - "/tmp/foo.csv"
    outputs:
      artifacts:
        - name: "seal-tags-csv"
          path: "/tmp/foo.gpkg"
