apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ogdc-recipe-arctic-circle-
  labels:
    workflows.argoproj.io/archive-strategy: 'false'
  annotations:
    workflows.argoproj.io/description: "The Arctic Circle is an imaginary line that\
      \ circles the globe at\napproximately 66\xB0 34' N and marks the latitude above\
      \ which the sun does\nnot set on the summer solstice, and does not rise on the\
      \ winter\nsolstice."
    qgreenlandLayerId: arctic_circle
spec:
  entrypoint: main
  templates:
  - name: main
    steps:
    - - name: step-0
        inline:
          container:
            image: ghcr.io/osgeo/gdal:alpine-normal-3.9.0
            command:
            - ogr2ogr
            args:
            - -lco
            - ENCODING=UTF-8
            - -t_srs
            - EPSG:3413
            - -clipdst
            - /tmp/assets_dir/latitude_shape_40_degrees.geojson
            - -makevalid
            - -segmentize
            - '1'
            - -s_srs
            - EPSG:4326
            - /tmp/output_dir/arctic_circle.gpkg
            - /tmp/input_dir/arctic_circle.geojson
            volumeMounts:
            - name: output-mount
              mountPath: /tmp/output_dir
          volumes:
          - name: output-mount
            emptyDir: {}
          inputs:
            artifacts:
            - name: step-0-assets_dir
              path: /tmp/assets_dir/latitude_shape_40_degrees.geojson
              http:
                url: https://raw.githubusercontent.com/nsidc/qgreenland/v3.0.0/qgreenland/assets/latitude_shape_40_degrees.geojson
            - name: step-0-input_dir
              path: /tmp/input_dir/arctic_circle.geojson
              http:
                url: https://raw.githubusercontent.com/nsidc/qgreenland/v3.0.0/qgreenland/assets/arctic_circle.geojson
          outputs:
            artifacts:
            - name: step-0-output_dir
              path: /tmp/output_dir
