apiVersion: "argoproj.io/v1alpha1"
kind: "Workflow"
metadata:
  generateName: "ogdc-recipe-ice-basins-pdg-"
  labels:
    # TODO: What is?
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a spike on creating PDG visualization tiles for the QGreenland
      ice basins layer
spec:
  entrypoint: "main"
  templates:
  - name: "main"
    dag:
      tasks:
        # # NOTE: This step is only needed to batch many input files; we have
        # # just one. Come back to this!
        # - name: "batch"
        #   inline:
        #     container:
        #       image: "python:alpine3.9"
        #       command: ["python"]
        #       source: |
        #         return [items[i:i + batch_size] for i in range(0, len(items), batch_size)]

        - name: "stage"
          inline:

            inputs:
              artifacts:
                - &viz-config-json-artifact
                  name: "viz-config-json"
                  path: "/tmp/config.json"
                  http:
                    url: "https://gist.githubusercontent.com/mfisher87/f13f87949809a4eef0485f3eb05b9534/raw/572f00bb76a7cb0b50a87078e4f8d9f7b8841818/qgnet_config.json"
                - name: "staging-input"
                  path: "/tmp/pdg_processing/input/ice_basins.gpkg"
                  http:
                    # url: "https://nsidc.org/qgreenland/layers/ice_basins/ice_basins.gpkg"
                    url: "https://github.com/QGreenland-Net/argo-exploration/raw/medium-workflow/data/Ice_Basins_1000.gpkg"

            container:
              image: "ghcr.io/mfisher87/pdgstaging"
              command: ["python"]
              args:
                - "-m"
                - "pdgstaging"
                - "-c"
                - "/tmp/config.json"

            outputs:
              # NOTE: We expected the output to contain z-levels 0,1,2,...,13
              # (as specified by JSON config input), but it only contained
              # 13. TODO: Figure out if we're using pdgstaging wrong or if
              # it's a bug??
              artifacts:
                - name: "staging-output"
                  # NOTE: Matches config!
                  path: "/tmp/pdg_processing/output/staged"

        - name: "rasterize"
          dependencies: ["stage"]
          inline:

            inputs:
              artifacts:
                - *viz-config-json-artifact
                - name: "staging-output"
                  from: "{{ steps.stage.outputs.artifacts.staging-output }}"
                    # path: "{{ steps.stage.outputs.artifacts.staging-output.path }}"
                  path: "/tmp/foo"

            container:
              # TODO: Dockerize the pdgraster library
              image: "ghcr.io/permafrostdiscoverygateway/viz-workflow:0.2.3"
              command: ["python"]
              args:
                - "-m"
                - "pdgraster"
                - "-c"
                - "/tmp/config.json"

            outputs:
              artifacts:
                - name: "raster-output"
                  path: "/tmp/pdg_processing/output/raster"
